[keys]
menu=45
hud=161
target=0
auto=82
aim=0
panic=35
[ui]
hudOn=0
xyz=0
block=0
angles=0
dir=0
status=1
playerNew=0
onlyInGame=0
opacity=25
scale=108
accent=4
x=0
y=0
sound=1
[auto]
on=0
crit=1
players=1
hostile=1
passive=1
ignoreTamed=0
dist10=29
delayMin=0
delayMax=0
[aim]
on=0
hostile=0
passive=0
tamed=0
los=1
players=1
range=12
fov=60
speed=374
slow=25
spread100=60
jitter100=15
flick100=40
[panic]
exit=1
[agent]
;java=C:\Program Files\Java\jdk-21\bin\java.exe
;jar=C:\path\to\mcagent.jar
[esp]
on=0
players=1
mobs=0
fill=1
range=64
[nametag]
on=0
hp=1
armor=1
hands=1
dist=0
